//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeBiometricData
    {
        public int EmployeeBioMetricDataId { get; set; }
        public int EmployeeId { get; set; }
        public string RightThumb { get; set; }
        public string RightIndexFinger { get; set; }
        public string RightMiddleFinger { get; set; }
        public string RightRingFinger { get; set; }
        public string RightLittleFinger { get; set; }
        public string LefttThumb { get; set; }
        public string LeftIndexFinger { get; set; }
        public string LeftMiddleFinger { get; set; }
        public string LeftRingFinger { get; set; }
        public string LeftLittleFinger { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
