//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int InvoiceId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> RegistrationFee { get; set; }
        public Nullable<double> AdminFee { get; set; }
        public Nullable<bool> IsRenewal { get; set; }
        public Nullable<int> PaymentMethodId { get; set; }
        public Nullable<int> PackageId { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> Total { get; set; }
        public string Comments { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Package Package { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
    }
}
